services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: chiliuser
      POSTGRES_PASSWORD: chilipass
      POSTGRES_DB: chilicake
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
